# Generated by Django 4.0.5 on 2022-07-20 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainCore', '0003_rename_teacher_id_classe_teacher_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(default='2018-10-23')),
                ('status', models.BooleanField(default='True')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainCore.eleve')),
            ],
        ),
    ]
